### ISSUE TITLE
PDF: Custom charset when using "FreeSerif" font uses Italics instead of Regular

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1072]
From:
* https://github.com/metanorma/pdfa-iso-32000-2/issues/32

<img width="775" alt="Screenshot 2023-12-22 at 10 33 39 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/7d72cfb0-aae5-4517-a0e8-92d2a99d141a">
<img width="770" alt="Screenshot 2023-12-22 at 10 33 45 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/c5e1b394-2ff6-42ee-9d84-b7863bccea78">

```adoc
:fonts: D050000L;TeXGyreTermes;STIX Two Math;FreeSerif;FreeSans
:presentation-metadata-custom-charset-font: dingbats:"D050000L",agl:"TeXGyreTermes",math:"STIX Two Math",serif:"FreeSerif",sans:"FreeSans"
```

```yaml
  - name: registersans
    entity: "[custom-charset: sans]#&#xAE;#"
    code: 342

  - name: registerserif
    entity: "[custom-charset: serif]#&#xAE;#"
    code: 322
```
