### ISSUE TITLE
Publishing an ISO collection that encodes ISO bibliographic data (ISO SMRL)

### ISSUE THREAD

**Issue by stuartgalt** [metanorma/metanorma-iso#1217]
I need to be able to publish a new document type that does not have a "document number" but is an ISO product that is a collection of ISO 10303 documents.  The title page is a bit different it looks like 

![image](https://github.com/user-attachments/assets/beddc6af-f33e-4505-ac3d-c65aca7d3255)

Perhaps the SUMA architecture may be applied to assist building this collection document type.

**Comment by opoudjis** [comment]
Metanorma collection manifests already are pretty much normal Metanorma document bibdata.

**Comment by ronaldtse** [comment]
Can we make them identical? I.e. embed a bibdata inside collection.yml.

**Comment by opoudjis** [comment]
> Can we make them identical? I.e. embed a bibdata inside collection.yml.

When I say "are pretty much normal Metanorma document bibdata", I actually mean "are identical to normal Metanorma document bibdata".

**Comment by opoudjis** [comment]
This task seems to be restricted to:

* Populating the bibdata for the collection (and providing guidance to @manuelfuenmayor to propagate that into Liquid)
* Providing a cover page Liquid template that renders the bibliographic data in the expected places

@ronaldtse Correct?

**Comment by opoudjis** [comment]
No response from @ronaldtse @stuartgalt @TRThurman 

So, the bibdata representation of Relaton metadata in YAML is given in https://www.relaton.org/specs/relaton-yaml/ . I am not happy with the fact that this representation cleaves so close to the internal representation of the bibliographic resource object, to an extent that the XML does not.

I don't see why it is my job to provide metadata here, when that is an editorial task, but the YAML for https://www.iso.org/publication/PUB100485.html looks like:

````
bibdata:
  title:
    - type: main
       content: STEP Module and Resource Library (SMRL)
  type: standard
  edition: "11"
  docid:
    type: SMRL
    id: 2024(E)
  flavor: iso
  date:
    - type: published
       on: 2024 
  ext:
    ics: 25.040.40
    price-code: XL
  copyright:
     owner:
       name: International Organization for Standardization
       abbreviation: ISO
       url: www.iso.org
     from: '2024'
  contributor:
    - organization:
        name: International Organization for Standardization
        url: www.iso.org
        abbreviation: ISO
      role:
        type: publisher
````

I will work out next how to get this into cover.html so that it looks like the current cover page.

I'm not sure that price-code will be recognised at all; it is currently only supported in IEC and not ISO.
