### ISSUE TITLE
gem size +200% because of test assets

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-iso#787]
- [2.1.8](https://rubygems.org/gems/metanorma-iso/versions/2.1.8) - September 06, 2022 (5.57 MB)
 - [2.1.7](https://rubygems.org/gems/metanorma-iso/versions/2.1.7) - August 23, 2022 (1.66 MB)

@opoudjis @ronaldtse should we do something about this?

**Comment by ronaldtse** [comment]
Absolutely we should act on this. Tests and specs are NOT supposed to be in the gems. 

What's the best way to do a bulk check on the gemspec include line?

**Comment by opoudjis** [comment]
The difference appears to have been triggered by the CIMAS update in https://github.com/metanorma/metanorma-iso/commit/72343a7ecca431c964b62734d980eda9cc0710b4 -- I don't see what else could have done this.

````
# Auto-generated by Cimas: Do not edit it manually!
# See https://github.com/metanorma/cimas
name: release

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'skip'
  push:
    tags: [ v* ]

jobs:
  release:
    uses: metanorma/ci/.github/workflows/rubygems-release.yml@main
    with:
      next_version: ${{ github.event.inputs.next_version }}
    secrets:
      rubygems-api-key: ${{ secrets.METANORMA_CI_RUBYGEMS_API_KEY }}
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
````

Presumably, this means that GHA had a workflow that overrided what gemspecs included, and now it doesn't.

Gemspecs in Metanorma are quite random in their inclusions, but this appears to be a good model:

````
spec.files         = `git ls-files -z`.split("\x0").reject do |f|
    f.match(%r{^(test|spec|features)/})
  end
````

I never use test or features, but I'm going to copy that across all my gemspecs. metanorma-iso currently has just `spec.files         = `git ls-files`.split("\n")`
