### ISSUE TITLE
ModSpec: Conformance tests with more than one corresponding Requirement show no correspondence

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-iso#808]
In relation to ISO 19115-3: https://github.com/metanorma/iso-19115-3/pull/18

Taking "https://standards.iso.org/iso19115/-1/1/req/metadata-xml/identification/associated-resource" as example, this requirement
shares target with another requirement:

```yaml
    - name: Validate with Schematron
      identifier: https://standards.iso.org/iso19115/-1/1/conf/metadata-xml/identification/schematron-rules
      targets:
      - https://standards.iso.org/iso19115/-1/1/req/metadata-xml/identification/topic-category
      - https://standards.iso.org/iso19115/-1/1/req/metadata-xml/identification/associated-resource
      method: Validate with mri.sch
```

In cases like this, a mesage error rises:

````
Requirements: (XML Line 002256):
Requirement https://standards.iso.org/iso19115/-1/1/req/metadata-xml/identification/associated-resource
has no corresponding Conformance test

````
